services:
  db_postgresql:
    image: bitnami/postgresql:latest
    env_file: ./.env
    volumes:
      - postgresql_data:/bitnami/postgresql
    networks:
      - kk_network
  sso_keycloak:
    image: bitnami/keycloak:26.2.0
    ports:
      - "8080:8080"
    expose:
      - "8080"
    env_file: ./.env
    depends_on:
      - db_postgresql
    networks:
      - kk_network
  kms:
    image: ghcr.io/cosmian/kms:latest
    container_name: kk_kms
    ports:
      - "443:443"
    volumes:
      - ./cosmian-kms:/root/cosmian-kms/sqlite-data
      - ./kms.toml:/etc/cosmian/kms.toml
      - ./cosmian-kms.p12:/etc/ssl/kms/cosmian-kms.p12
    restart: none
    networks:
      - kk_network
networks:
  kk_network:
    driver: bridge
